@Banking.WebApi_HostAddress = http://localhost:5078

POST {{Banking.WebApi_HostAddress}}/api/v1/account/
Content-Type: application/json

{
  "firstName": "pipat",
  "lastName": "posawad",
  "amount": 1000
}

###

POST {{Banking.WebApi_HostAddress}}/api/v1/account/deposit/
Content-Type: application/json

{
  "accountNumber": "NL87IUTW1900990570",
  "amount": "500"
}

###

POST {{Banking.WebApi_HostAddress}}/api/v1/account/transfer/
Content-Type: application/json

{
  "fromAccountNumber": "NL87IUTW1900990570",
  "toAccountNumber": "NL37BMNE6490800710",
  "amount": "100"
}

###