@Banking.WebApi_HostAddress = http://localhost:5078

POST {{Banking.WebApi_HostAddress}}/api/v1/account/
Content-Type: application/json

{
  "firstName": "pipat",
  "lastName": "posawad",
  "amount": 0
}

###

POST {{Banking.WebApi_HostAddress}}/api/v1/account/deposit/
Content-Type: application/json

{
  "accountNumber": "NL11EZQW5759040389",
  "amount": "1000"
}

###

POST {{Banking.WebApi_HostAddress}}/api/v1/account/transfer/
Content-Type: application/json

{
  "fromAccountNumber": "NL11EZQW5759040389",
  "toAccountNumber": "NL92GDAV6888200556",
  "amount": "900"
}

###